# Generated by Django 5.2.8 on 2025-12-03 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('additional', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Social',
            new_name='SocialLink',
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'about'},
        ),
        migrations.AlterModelOptions(
            name='sociallink',
            options={'verbose_name_plural': 'social'},
        ),
    ]
