# Generated by Django 5.2.8 on 2025-12-03 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('additional', '0002_rename_social_sociallink_alter_about_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallink',
            options={},
        ),
    ]
